<option value="">select</option>
<option value="Afghanistan">Afghanistan</option>
<option value="Argentina">Argentina</option>
<option value="Australia">Australia</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Bosnia and Herzegovina">Bosnia and Herzegovina</option>
<option value="Brazil">Brazil</option>
<option value="Canada">Canada</option>
<option value="China">China</option>
<option value="Croatia">Croatia</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Egypt">Egypt</option>
<option value="France">France</option>
<option value="Germany">Germany</option>
<option value="Greece">Greece</option>
<option value="India">India</option>
<option value="Israel">Israel</option>
<option value="Italy">Italy</option>
<option value="Japan">Japan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Korea">Korea</option>
<option value="Kyrgyzstan">Kyrgyzstan</option>
<option value="Malaysia">Malaysia</option>
<option value="Portugal">Portugal</option>
<option value="Russian Federation">Russian Federation</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Spain">Spain</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Turkey">Turkey</option>
<option value="United States">United States</option>
<option value="Uzbekistan">Uzbekistan</option>